services:
  mycudaapp:
    build:
      context: .
    ports:
      - "8888:8888"  # Map host port 8888 to container port 8888 for Jupyter Notebook
      - "8889:8889"  # Map host port 8888 to container port 8888 for Jupyter Notebook
    volumes:
      - ./maskrcnn-lgpma-pub-e12-pub.pth:/app/DAVAR-Lab-OCR/test/maskrcnn-lgpma-pub-e12-pub.pth 
    command: ["sleep", "infinity"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

